from os import environ
SESSION_CONFIG_DEFAULTS = dict(
    real_world_currency_per_point=1, participation_fee=0
)
SESSION_CONFIGS = [
    dict(
        name='BSR_Low_10ball_ProlificPilot',
        app_sequence=[
            'randomization_id',
            'belief_instructions',
        ],
        num_demo_participants=3,
        showupfee=2,
        bsr=1,
        qsr=0,
        flat=0,
        stakeshigh=0,
        stakeshighval=15,
        stakeslowval=1.5,
        stakesflatval=15,
        ambiguityfirst=1,
        full_screen=True,
        live_ping=False,
        audio=True,
        numballs=10,
        simple_instruction=False,
        testing=0,
        randomizationfile='data/randomization_numballs_10.csv',
        randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_10_locked.xlsx',
        password='ExperimentDieRolls2022',
        prolific=True,
        instructionpilot=False,
        video1link='global/video/bsr_sub_1.mp4',
        video2link='global/video/bsr_low_sub_2.mp4',
        video3link='global/video/bsr_low_sub_3.mp4',
        prolificcompletionID='AAAAAA',
    ),
    # dict(
    #     name='BSR_Low_100ball_ProlificPilot',
    #     app_sequence=[
    #         'introduction',
    #         'randomization_id',
    #         'belief_instructions',
    #         'belief_task',
    #         'questionnaire',
    #         'prolific_survey',
    #         'payment',
    #         'end',
    #     ],
    #     num_demo_participants=3,
    #     showupfee=2,
    #     bsr=1,
    #     qsr=0,
    #     flat=0,
    #     stakeshigh=0,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    #     simple_instruction=False,
    #     testing=0,
    #     randomizationfile='data/randomization_numballs_100.csv',
    #     randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_100_locked.xlsx',
    #     password='ExperimentDieRolls2022',
    #     prolific=True,
    #     instructionpilot=False,
    #     video1link='global/video/bsr_sub_1.mp4',
    #     video2link='global/video/bsr_low_sub_2.mp4',
    #     video3link='global/video/bsr_low_sub_3.mp4',
    #     prolificcompletionID='AAAAAA',
    # ),
    # dict(
    #     name='BSR_High_100ball_ProlificInsPilot_Simple',
    #     app_sequence=[
    #         'introduction',
    #         'belief_instructions',
    #         'prolific_survey',
    #         'end',
    #     ],
    #     num_demo_participants=3,
    #     showupfee=2,
    #     bsr=1,
    #     qsr=0,
    #     flat=0,
    #     stakeshigh=1,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    #     simple_instruction=True,
    #     testing=0,
    #     randomizationfile='data/randomization_numballs_100.csv',
    #     randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_100_locked.xlsx',
    #     password='ExperimentDieRolls2022',
    #     prolific=True,
    #     instructionpilot=True,
    #     video1link='global/video/bsr_sub_1.mp4',
    #     video2link='global/video/bsr_high_sub_2.mp4',
    #     video3link='global/video/bsr_high_sub_3.mp4',
    #     prolificcompletionID='AAAAAA',
    # ),
    # dict(
    #     name='BSR_High_100ball_ProlificInsPilot_Video',
    #     app_sequence=[
    #         'introduction',
    #         'belief_instructions',
    #         'prolific_survey',
    #         'end',
    #     ],
    #     num_demo_participants=3,
    #     showupfee=2,
    #     bsr=1,
    #     qsr=0,
    #     flat=0,
    #     stakeshigh=1,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    #     simple_instruction=False,
    #     testing=0,
    #     randomizationfile='data/randomization_numballs_100.csv',
    #     randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_100_locked.xlsx',
    #     password='ExperimentDieRolls2022',
    #     prolific=True,
    #     instructionpilot=True,
    #     video1link='global/video/bsr_sub_1.mp4',
    #     video2link='global/video/bsr_high_sub_2.mp4',
    #     video3link='global/video/bsr_high_sub_3.mp4',
    #     prolificcompletionID='AAAAAA',
    # ),
    # dict(
    #     name='BSR_High_100ball_Video',
    #     app_sequence=[
    #         'introduction',
    #         'randomization_id',
    #         'belief_instructions',
    #         'belief_task',
    #         'risk_elicitation',
    #         'ambiguity_elicitation',
    #         'questionnaire',
    #         'payment',
    #         'end',
    #     ],
    #     num_demo_participants=3,
    #     showupfee=6,
    #     bsr=1,
    #     qsr=0,
    #     flat=0,
    #     stakeshigh=1,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    #     simple_instruction=False,
    #     testing=0,
    #     randomizationfile='data/randomization_numballs_100.csv',
    #     randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_100_locked.xlsx',
    #     password='ExperimentDieRolls2022',
    #     prolific=False,
    #     instructionpilot=False,
    #     video1link='global/video/bsr_sub_1.mp4',
    #     video2link='global/video/bsr_high_sub_2.mp4',
    #     video3link='global/video/bsr_high_sub_3.mp4',
    #     prolificcompletionID='AAAAAA',
    # ),
    # dict(
    #     name='BSR_Low_100ball_Video',
    #     app_sequence=[
    #         'introduction',
    #         'randomization_id',
    #         'belief_instructions',
    #         'belief_task',
    #         'risk_elicitation',
    #         'ambiguity_elicitation',
    #         'questionnaire',
    #         'payment',
    #         'end',
    #     ],
    #     num_demo_participants=3,
    #     showupfee=6,
    #     bsr=1,
    #     qsr=0,
    #     flat=0,
    #     stakeshigh=0,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    #     simple_instruction=False,
    #     testing=0,
    #     randomizationfile='data/randomization_numballs_100.csv',
    #     randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_100_locked.xlsx',
    #     password='ExperimentDieRolls2022',
    #     prolific=False,
    #     instructionpilot=False,
    #     video1link='global/video/bsr_sub_1.mp4',
    #     video2link='global/video/bsr_low_sub_2.mp4',
    #     video3link='global/video/bsr_low_sub_3.mp4',
    #     prolificcompletionID='AAAAAA',
    # ),
    # dict(
    #     name='QSR_High_100ball_Video',
    #     app_sequence=[
    #         'introduction',
    #         'randomization_id',
    #         'belief_instructions',
    #         'belief_task',
    #         'risk_elicitation',
    #         'ambiguity_elicitation',
    #         'questionnaire',
    #         'payment',
    #         'end',
    #     ],
    #     num_demo_participants=3,
    #     showupfee=6,
    #     bsr=0,
    #     qsr=1,
    #     flat=0,
    #     stakeshigh=1,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    #     simple_instruction=False,
    #     testing=0,
    #     randomizationfile='data/randomization_numballs_100.csv',
    #     randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_100_locked.xlsx',
    #     password='ExperimentDieRolls2022',
    #     prolific=False,
    #     instructionpilot=False,
    #     video1link='global/video/qsr_sub_1.mp4',
    #     video2link='global/video/qsr_high_sub_2.mp4',
    #     video3link='global/video/qsr_high_sub_3.mp4',
    #     prolificcompletionID='AAAAAA',
    # ),
    # dict(
    #     name='QSR_Low_100ball_Video',
    #     app_sequence=[
    #         'introduction',
    #         'randomization_id',
    #         'belief_instructions',
    #         'belief_task',
    #         'risk_elicitation',
    #         'ambiguity_elicitation',
    #         'questionnaire',
    #         'payment',
    #         'end',
    #     ],
    #     num_demo_participants=3,
    #     showupfee=6,
    #     bsr=0,
    #     qsr=1,
    #     flat=0,
    #     stakeshigh=0,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    #     simple_instruction=False,
    #     testing=0,
    #     randomizationfile='data/randomization_numballs_100.csv',
    #     randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_100_locked.xlsx',
    #     password='ExperimentDieRolls2022',
    #     prolific=False,
    #     instructionpilot=False,
    #     video1link='global/video/qsr_sub_1.mp4',
    #     video2link='global/video/qsr_low_sub_2.mp4',
    #     video3link='global/video/qsr_low_sub_3.mp4',
    #     prolificcompletionID='AAAAAA',
    # ),
    # dict(
    #     name='BSR_High_100ball_Simple',
    #     app_sequence=[
    #         'introduction',
    #         'randomization_id',
    #         'belief_instructions',
    #         'belief_task',
    #         'risk_elicitation',
    #         'ambiguity_elicitation',
    #         'questionnaire',
    #         'payment',
    #         'end',
    #     ],
    #     num_demo_participants=3,
    #     showupfee=6,
    #     bsr=1,
    #     qsr=0,
    #     flat=0,
    #     stakeshigh=1,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    #     simple_instruction=True,
    #     testing=0,
    #     randomizationfile='data/randomization_numballs_100.csv',
    #     randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_100_locked.xlsx',
    #     password='ExperimentDieRolls2022',
    #     prolific=False,
    #     instructionpilot=False,
    #     video1link='global/video/bsr_sub_1.mp4',
    #     video2link='global/video/bsr_high_sub_2.mp4',
    #     video3link='global/video/bsr_high_sub_3.mp4',
    #     prolificcompletionID='AAAAAA',
    # ),
    # dict(
    #     name='BSR_Low_100ball_Simple',
    #     app_sequence=[
    #         'introduction',
    #         'randomization_id',
    #         'belief_instructions',
    #         'belief_task',
    #         'risk_elicitation',
    #         'ambiguity_elicitation',
    #         'questionnaire',
    #         'payment',
    #         'end',
    #     ],
    #     num_demo_participants=3,
    #     showupfee=6,
    #     bsr=1,
    #     qsr=0,
    #     flat=0,
    #     stakeshigh=0,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    #     simple_instruction=True,
    #     testing=0,
    #     randomizationfile='data/randomization_numballs_100.csv',
    #     randomizationfile_locked='https://boonhankoh.github.io/bhk-econ/experiment/randomization_numballs_100_locked.xlsx',
    #     password='ExperimentDieRolls2022',
    #     prolific=False,
    #     instructionpilot=False,
    #     video1link='global/video/bsr_sub_1.mp4',
    #     video2link='global/video/bsr_low_sub_2.mp4',
    #     video3link='global/video/bsr_low_sub_3.mp4',
    #     prolificcompletionID='AAAAAA',
    # ),
    # dict(
    #     name='Randomization_100ball',
    #     app_sequence=[
    #         'randomization',
    #     ],
    #     num_demo_participants=100,
    #     showupfee=6,
    #     bsr=0,
    #     qsr=1,
    #     flat=0,
    #     stakeshigh=1,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=100,
    # ),
    # dict(
    #     name='Randomization_10ball',
    #     app_sequence=[
    #         'randomization',
    #     ],
    #     num_demo_participants=100,
    #     showupfee=6,
    #     bsr=0,
    #     qsr=1,
    #     flat=0,
    #     stakeshigh=1,
    #     stakeshighval=15,
    #     stakeslowval=1.5,
    #     stakesflatval=15,
    #     ambiguityfirst=1,
    #     full_screen=True,
    #     live_ping=False,
    #     audio=True,
    #     numballs=10,
    # ),
]

# if you set a property in SESSION_CONFIG_DEFAULTS, it will be inherited by all configs
# in SESSION_CONFIGS, except those that explicitly override it.
# the session config can be accessed from methods in your apps as self.session.config,
# e.g. self.session.config['participation_fee']

# ISO-639 code
# for example: de, fr, ja, ko, zh-hans
LANGUAGE_CODE = 'en'
# e.g. EUR, GBP, CNY, JPY
REAL_WORLD_CURRENCY_CODE = 'EUR'
USE_POINTS = False
# POINTS_CUSTOM_NAME = "tokens"
REAL_WORLD_CURRENCY_DECIMAL_PLACES = 1
DEMO_PAGE_INTRO_HTML = ''
PARTICIPANT_FIELDS = ['is_dropout', 'dropout',
                      'randomizationID',
                      'order1', 'order2',
                      'riskfirst', 'ambiguityfirst',
                      'risky_urn5_color_code1', 'risky_urn5_color_code2', 'risky_urn2_color_code',
                      'risky_urn5_num_color1', 'risky_urn5_num_color2', 'risky_urn2_num_color',
                      'risky_urn5_colorevent1', 'risky_urn5_colorevent2', 'risky_urn2_colorevent',
                      'amb1_urn5_color_code1', 'amb1_urn5_color_code2', 'amb1_urn2_color_code',
                      'amb1_urn5_num_color1', 'amb1_urn5_num_color2', 'amb1_urn2_num_color',
                      'amb1_urn5_colorevent1', 'amb1_urn5_colorevent2', 'amb1_urn2_colorevent',
                      'amb2_urn5_color_code1', 'amb2_urn5_color_code2', 'amb2_urn2_color_code',
                      'amb2_urn5_num_color1', 'amb2_urn5_num_color2', 'amb2_urn2_num_color',
                      'prior1', 'prior2', 'prior3', 'prior4', 'prior5', 'prior6',
                      ]
SESSION_FIELDS = []

ROOMS = [
    dict(
        name='cdkw_1',
        display_name='Experiments in Individual Decision Making 1',
        participant_label_file='_rooms/experimenTUM.txt',
    ),
    dict(
        name='cdkw_2',
        display_name='Experiments in Individual Decision Making 2',
        participant_label_file='_rooms/experimenTUM.txt',
    ),
    dict(
        name='cdkw_3',
        display_name='Experiments in Individual Decision Making 3',
        participant_label_file='_rooms/experimenTUM.txt',
    ),
    dict(
        name='cdkw_4',
        display_name='Experiments in Individual Decision Making 4',
        participant_label_file='_rooms/experimenTUM.txt',
    ),
    ]

ADMIN_USERNAME = 'admin'
# for security, best to set admin password in an environment variable
ADMIN_PASSWORD = environ.get('OTREE_ADMIN_PASSWORD')

SECRET_KEY = 'blahblah'

# if an app is included in SESSION_CONFIGS, you don't need to list it here
INSTALLED_APPS = [
    'otree',
    'django.contrib.humanize',
]
